<a href="https://colab.research.google.com/github/lathika4/ML_23AG1A66H0/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
list1=[2,3,4,5]
arr1=np.array(list1)
print(arr1)

[2 3 4 5]


In [3]:
arr1=np.array([2,3,4,5])
print(arr1)

[2 3 4 5]


In [11]:
arr=np.array([[2,3,4,5],[3,4,5,6]])
print(arr)

[[2 3 4 5]
 [3 4 5 6]]


In [7]:
arr1=np.array([[[2,3,4,5],[3,4,5,6],[6,7,8,9]]])
print(arr1)

[[[2 3 4 5]
  [3 4 5 6]
  [6 7 8 9]]]


In [8]:
print(arr1.dtype)

int64


In [9]:
print(arr1.ndim)

3


In [12]:
print(arr.size)

8


In [14]:
print(arr1.shape)

(1, 3, 4)


In [15]:
print(arr.shape)

(2, 4)


In [16]:
print(arr1.itemsize)

8


In [20]:
array1 = np.array([6, 7, 8])
array2 = np.array([[1, 2, 3],
                   	    [6, 7, 8]])

print("\nData of array1 is: ",array1.data)
print("Data of array2 is: ",array2.data)


Data of array1 is:  <memory at 0x79193abde500>
Data of array2 is:  <memory at 0x79193acaf5e0>


In [21]:
array1 = np.array([1, 3, 5, 7, 9])


print(array1[0])
print(array1[2])
print(array1[4])

1
5
9


In [23]:
array1[1]=10
print(array1)


[ 1 10  5  7  9]


In [24]:
array1 = np.array([[1, 3, 5, 7],
                       [9, 11, 13, 15],
                       [2, 4, 6, 8]])


element1 = array1[1, 3]
print("4th Element at 2nd Row:",element1)


element2 = array1[0, 1]
print("2nd Element at First Row:",element2)

4th Element at 2nd Row: 15
2nd Element at First Row: 3


In [25]:
array1 = np.array([1, 2, 3, 4, 5])


median = np.median(array1)

print(median)

3.0


In [26]:
marks = np.array([76, 78, 81, 66, 85])


std_marks = np.std(marks)
print(std_marks)

6.368673331236263
